### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by wyiite** [klicom/azumi-revamp#1]
### In this issue you can suggest features for azumi-revamp bot.

**Comment by Kusake** [comment]
Короча шоба когда кто-то пишет "Бот говно" он отвечал "Сам ты говно чувак" и так на британском языке тож пахаххах ну круто придумала да ага? да?.. ведь да..?..

**Comment by wyiite** [comment]
> Короча шоба когда кто-то пишет "Бот говно" он отвечал "Сам ты говно чувак" и так на британском языке тож пахаххах ну круто придумала да ага? да?.. ведь да..?..

Ну я же попросил нормальных идей, а не говна в **Issue** накидать.

**Comment by DmitryFisk** [comment]
да просто блочь таких ебланов, и всё

**Comment by wyiite** [comment]
> да просто блочь таких ебланов, и всё

ладно.
